assistant: AskBot  # Current choices: AskBot
models:
  chat:
    chat: gpt-4o-mini  # e.g., gpt-4o-mini, gpt-4o, gpt-4-turbo, mock-model
paths:  
  # Paths can be specified as either absolute or relative:
  # - Absolute: Paths that start with "/" (or a drive letter and ":\\" on windows) and represent the full path from the root directory of the filesystem.
  # - Relative: Do not start with "/" and are relative to the location of this config file.
  assistants: assistants/
